2021-10-14 11:33:36,192 INFO    MainThread:992 [wandb_setup.py:_flush():69] setting env: {}
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211014_113336-341ne5li/logs/debug.log
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211014_113336-341ne5li/logs/debug-internal.log
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_init.py:init():375] calling init triggers
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/bio_dataset/bio_ner_dataset_fam.csv', 'checkpoint_path': '/root/konst/model_checkpoints/ner_employment', 'model_path': 'ner_base_epoch_12_acc_10.1566_vs_1.5907_loss_0.0643_vs_0.0574.pth', 'batch_size': 128, 'epochs': 160, 'start_epoch': 0, 'test_size': 0.05, 'lam': 0, 'patience': 5, 'factor': 0.5, 'use_wandb': True, 'lr': 0.001, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 4}
2021-10-14 11:33:36,193 INFO    MainThread:992 [wandb_init.py:init():424] starting backend
2021-10-14 11:33:36,193 INFO    MainThread:992 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-14 11:33:36,206 INFO    MainThread:992 [backend.py:ensure_launched():135] starting backend process...
2021-10-14 11:33:36,211 INFO    MainThread:992 [backend.py:ensure_launched():140] started backend process with pid: 1007
2021-10-14 11:33:36,212 INFO    MainThread:992 [wandb_init.py:init():429] backend started and connected
2021-10-14 11:33:36,214 INFO    MainThread:992 [wandb_init.py:init():477] updated telemetry
2021-10-14 11:33:36,215 INFO    MainThread:992 [wandb_init.py:init():500] communicating current version
2021-10-14 11:33:36,684 INFO    MainThread:992 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-14 11:33:36,684 INFO    MainThread:992 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-14 11:33:36,872 INFO    MainThread:992 [wandb_init.py:init():540] starting run threads in backend
2021-10-14 11:33:37,639 INFO    MainThread:992 [wandb_run.py:_console_start():1584] atexit reg
2021-10-14 11:33:37,639 INFO    MainThread:992 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-10-14 11:33:37,640 INFO    MainThread:992 [wandb_run.py:_redirect():1463] Redirecting console.
2021-10-14 11:33:37,641 INFO    MainThread:992 [wandb_run.py:_redirect():1519] Redirects installed.
2021-10-14 11:33:37,641 INFO    MainThread:992 [wandb_init.py:init():565] run started, returning control to user process
2021-10-14 12:21:13,521 INFO    MainThread:992 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 255
2021-10-14 12:21:13,522 INFO    MainThread:992 [wandb_run.py:_restore():1526] restore
