
  0%|                                                                                                                | 0/4621 [00:00<?, ?it/s]
0.133604





















































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































































Epoch: 0/99 Phase: train Loss: 0.3922 (0.3921) Acc: 0.0028 (0.0032) Acc PER: 0.8205 (0.7895):  70%|████▉  | 3240/4621 [57:28<24:29,  1.06s/it]
Traceback (most recent call last):
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 90, in rebuild_tensor
    t = torch._utils._rebuild_tensor(storage, storage_offset, size, stride)
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/_utils.py", line 131, in _rebuild_tensor
    return t.set_(storage, storage_offset, size, stride)
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 15227) is killed by signal: Killed.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "train.py", line 314, in <module>
    wandb,
  File "train.py", line 79, in train
    for idx, sample in pbar:
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/tqdm/std.py", line 1133, in __iter__
    for obj in iterable:
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/root/virtualenvs/pytorch_1.4/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 15227) exited unexpectedly