2021-10-05 21:58:12,266 INFO    MainThread:2890 [wandb_setup.py:_flush():69] setting env: {}
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '8bbaf831241b8525faf8ba0890cc99d295161186'}
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_setup.py:_flush():69] setting login settings: {}
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_init.py:_log_setup():342] Logging user logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211005_215812-nijwnzox/logs/debug.log
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_init.py:_log_setup():343] Logging internal logs to /root/konst/ml-utils/training/ner_employment/wandb/run-20211005_215812-nijwnzox/logs/debug-internal.log
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_init.py:init():375] calling init triggers
2021-10-05 21:58:12,267 INFO    MainThread:2890 [wandb_init.py:init():382] wandb.init called with sweep_config: {}
config: {'data_path': '/root/konst/data/bio_dataset/bio_ner_dataset.csv', 'checkpoint_path': '/root/konst/model_checkpoints/ner_employment', 'model_path': '', 'batch_size': 128, 'epochs': 40, 'start_epoch': 0, 'test_size': 0.05, 'lam': 0, 'patience': 5, 'factor': 0.5, 'use_wandb': True, 'lr': 0.00015, 'save_at': 1, 'adjust_lr_every': 1, 'num_workers': 4}
2021-10-05 21:58:12,268 INFO    MainThread:2890 [wandb_init.py:init():424] starting backend
2021-10-05 21:58:12,268 INFO    MainThread:2890 [backend.py:_multiprocessing_setup():72] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-10-05 21:58:12,281 INFO    MainThread:2890 [backend.py:ensure_launched():135] starting backend process...
2021-10-05 21:58:12,287 INFO    MainThread:2890 [backend.py:ensure_launched():140] started backend process with pid: 2905
2021-10-05 21:58:12,288 INFO    MainThread:2890 [wandb_init.py:init():429] backend started and connected
2021-10-05 21:58:12,290 INFO    MainThread:2890 [wandb_init.py:init():477] updated telemetry
2021-10-05 21:58:12,290 INFO    MainThread:2890 [wandb_init.py:init():500] communicating current version
2021-10-05 21:58:12,790 INFO    MainThread:2890 [wandb_init.py:init():505] got version response upgrade_message: "wandb version 0.12.4 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-10-05 21:58:12,790 INFO    MainThread:2890 [wandb_init.py:init():513] communicating run to backend with 30 second timeout
2021-10-05 21:58:13,019 INFO    MainThread:2890 [wandb_init.py:init():540] starting run threads in backend
2021-10-05 21:58:15,211 INFO    MainThread:2890 [wandb_run.py:_console_start():1584] atexit reg
2021-10-05 21:58:15,211 INFO    MainThread:2890 [wandb_run.py:_redirect():1458] redirect: SettingsConsole.REDIRECT
2021-10-05 21:58:15,212 INFO    MainThread:2890 [wandb_run.py:_redirect():1463] Redirecting console.
2021-10-05 21:58:15,215 INFO    MainThread:2890 [wandb_run.py:_redirect():1519] Redirects installed.
2021-10-05 21:58:15,215 INFO    MainThread:2890 [wandb_init.py:init():565] run started, returning control to user process
2021-10-05 21:58:55,069 INFO    MainThread:2890 [wandb_run.py:_atexit_cleanup():1554] got exitcode: 1
2021-10-05 21:58:55,070 INFO    MainThread:2890 [wandb_run.py:_restore():1526] restore
2021-10-05 21:58:57,634 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1139
  total_bytes: 1139
}

2021-10-05 21:58:57,855 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1139
  total_bytes: 1139
}

2021-10-05 21:58:58,043 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1139
  total_bytes: 8413
}

2021-10-05 21:58:58,145 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1139
  total_bytes: 8413
}

2021-10-05 21:58:58,248 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1139
  total_bytes: 8413
}

2021-10-05 21:58:58,351 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:58,455 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:58,558 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:58,662 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:58,765 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:59,201 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:58:59,304 INFO    MainThread:2890 [wandb_run.py:_wait_for_finish():1676] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 8413
  total_bytes: 8413
}

2021-10-05 21:59:00,496 INFO    MainThread:2890 [wandb_run.py:_show_files():1898] logging synced files
